version: '3'
services:
  worker:
    build: .
    env_file: .env
    command: sh run_celery.sh
    networks:
      - backend
    depends_on:
      - redis
      - postgres

  api:
    build: .
    env_file: .env
    environment:
      - FLASK_DEBUG=False
    command: sh run_api.sh
    networks:
      - traefik_webgateway
      - backend
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.vertogas.lab-apps.fr"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_webgateway"

  postgres:
    image: postgres:9.6-alpine
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    networks:
      - backend
    env_file: .env

networks:
  backend:
    driver: bridge
  traefik_webgateway:
    external: true


volumes:
  db-data:
    driver: local
