version: '3'
services:
  worker:
    build: .
    env_file: .env
    command: sh run_celery.sh
    networks:
      - backend
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - postgres

  api:
    build: .
    env_file: .env
    environment:
      - FLASK_DEBUG=True
    command: sh run_api.sh
    networks:
      - traefikportainer_webgateway
      - backend
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefikportainer_webgateway"

  postgres:
    image: postgres:9.6-alpine
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    networks:
      - backend
    env_file: .env

networks:
  backend:
    driver: bridge
  traefikportainer_webgateway:
    external: true


volumes:
  db-data:
    driver: local
